version: "3.8"
services:
  shoulder-demo-client:
    build:
      context: ./client
      dockerfile: ./client.DockerFile
    image: kitware/video-shoulder-demo-client:${TAG:-latest}
    ports:
     - "8000:8000"
  shoulder-demo-server:
    build:
      context: ./server
      dockerfile: ./server.DockerFile
    image: kitware/video-demo-server:${TAG:-latest}
    volumes:
      - type: bind
        source: ./data
        target: /data
        volume:
          nocopy: true
    ports:
     - "9000:9000"
